# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/command.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='files/command.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=b'\252\002\027UPC.CommunicatorObjects',
  serialized_pb=b'\n\x13\x66iles/command.proto\x12\x14\x63ommunicator_objects*W\n\x0c\x43ommandProto\x12\x08\n\x04STEP\x10\x00\x12\t\n\x05RESET\x10\x01\x12\x14\n\x10\x45PISODE_COMPLETE\x10\x02\x12\x12\n\x0eINITIALIZATION\x10\x08\x12\x08\n\x04QUIT\x10\tB\x1a\xaa\x02\x17UPC.CommunicatorObjectsb\x06proto3'
)

_COMMANDPROTO = _descriptor.EnumDescriptor(
  name='CommandProto',
  full_name='communicator_objects.CommandProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STEP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EPISODE_COMPLETE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INITIALIZATION', index=3, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=4, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=45,
  serialized_end=132,
)
_sym_db.RegisterEnumDescriptor(_COMMANDPROTO)

CommandProto = enum_type_wrapper.EnumTypeWrapper(_COMMANDPROTO)
STEP = 0
RESET = 1
EPISODE_COMPLETE = 2
INITIALIZATION = 8
QUIT = 9


DESCRIPTOR.enum_types_by_name['CommandProto'] = _COMMANDPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
