# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/unity_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlagents.communicator_objects import unity_output_pb2 as files_dot_unity__output__pb2
from mlagents.communicator_objects import unity_input_pb2 as files_dot_unity__input__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='files/unity_message.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=b'\252\002\027UPC.CommunicatorObjects',
  serialized_pb=b'\n\x19\x66iles/unity_message.proto\x12\x14\x63ommunicator_objects\x1a\x18\x66iles/unity_output.proto\x1a\x17\x66iles/unity_input.proto\"\xae\x01\n\x11UnityMessageProto\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12<\n\x0cunity_output\x18\x03 \x01(\x0b\x32&.communicator_objects.UnityOutputProto\x12:\n\x0bunity_input\x18\x04 \x01(\x0b\x32%.communicator_objects.UnityInputProtoB\x1a\xaa\x02\x17UPC.CommunicatorObjectsb\x06proto3'
  ,
  dependencies=[files_dot_unity__output__pb2.DESCRIPTOR,files_dot_unity__input__pb2.DESCRIPTOR,])




_UNITYMESSAGEPROTO = _descriptor.Descriptor(
  name='UnityMessageProto',
  full_name='communicator_objects.UnityMessageProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='communicator_objects.UnityMessageProto.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='communicator_objects.UnityMessageProto.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unity_output', full_name='communicator_objects.UnityMessageProto.unity_output', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unity_input', full_name='communicator_objects.UnityMessageProto.unity_input', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=277,
)

_UNITYMESSAGEPROTO.fields_by_name['unity_output'].message_type = files_dot_unity__output__pb2._UNITYOUTPUTPROTO
_UNITYMESSAGEPROTO.fields_by_name['unity_input'].message_type = files_dot_unity__input__pb2._UNITYINPUTPROTO
DESCRIPTOR.message_types_by_name['UnityMessageProto'] = _UNITYMESSAGEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnityMessageProto = _reflection.GeneratedProtocolMessageType('UnityMessageProto', (_message.Message,), {
  'DESCRIPTOR' : _UNITYMESSAGEPROTO,
  '__module__' : 'files.unity_message_pb2'
  # @@protoc_insertion_point(class_scope:communicator_objects.UnityMessageProto)
  })
_sym_db.RegisterMessage(UnityMessageProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
