# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files/unity_output.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlagents.communicator_objects import unity_initialization_output_pb2 as files_dot_unity__initialization__output__pb2
from mlagents.communicator_objects import command_pb2 as files_dot_command__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='files/unity_output.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=b'\252\002\027UPC.CommunicatorObjects',
  serialized_pb=b'\n\x18\x66iles/unity_output.proto\x12\x14\x63ommunicator_objects\x1a\'files/unity_initialization_output.proto\x1a\x13\x66iles/command.proto\"\x9c\x01\n\x10UnityOutputProto\x12S\n\x15initialization_output\x18\x01 \x01(\x0b\x32\x34.communicator_objects.UnityInitializationOutputProto\x12\x33\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\".communicator_objects.CommandProtoB\x1a\xaa\x02\x17UPC.CommunicatorObjectsb\x06proto3'
  ,
  dependencies=[files_dot_unity__initialization__output__pb2.DESCRIPTOR,files_dot_command__pb2.DESCRIPTOR,])




_UNITYOUTPUTPROTO = _descriptor.Descriptor(
  name='UnityOutputProto',
  full_name='communicator_objects.UnityOutputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initialization_output', full_name='communicator_objects.UnityOutputProto.initialization_output', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='communicator_objects.UnityOutputProto.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=269,
)

_UNITYOUTPUTPROTO.fields_by_name['initialization_output'].message_type = files_dot_unity__initialization__output__pb2._UNITYINITIALIZATIONOUTPUTPROTO
_UNITYOUTPUTPROTO.fields_by_name['command'].enum_type = files_dot_command__pb2._COMMANDPROTO
DESCRIPTOR.message_types_by_name['UnityOutputProto'] = _UNITYOUTPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnityOutputProto = _reflection.GeneratedProtocolMessageType('UnityOutputProto', (_message.Message,), {
  'DESCRIPTOR' : _UNITYOUTPUTPROTO,
  '__module__' : 'files.unity_output_pb2'
  # @@protoc_insertion_point(class_scope:communicator_objects.UnityOutputProto)
  })
_sym_db.RegisterMessage(UnityOutputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
