// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: files/command.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UPC.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from files/command.proto</summary>
  public static partial class CommandReflection {

    #region Descriptor
    /// <summary>File descriptor for files/command.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNmaWxlcy9jb21tYW5kLnByb3RvEhRjb21tdW5pY2F0b3Jfb2JqZWN0cypX",
            "CgxDb21tYW5kUHJvdG8SCAoEU1RFUBAAEgkKBVJFU0VUEAESFAoQRVBJU09E",
            "RV9DT01QTEVURRACEhIKDklOSVRJQUxJWkFUSU9OEAgSCAoEUVVJVBAJQhqq",
            "AhdVUEMuQ29tbXVuaWNhdG9yT2JqZWN0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::UPC.CommunicatorObjects.CommandProto), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CommandProto {
    [pbr::OriginalName("STEP")] Step = 0,
    [pbr::OriginalName("RESET")] Reset = 1,
    [pbr::OriginalName("EPISODE_COMPLETE")] EpisodeComplete = 2,
    [pbr::OriginalName("INITIALIZATION")] Initialization = 8,
    [pbr::OriginalName("QUIT")] Quit = 9,
  }

  #endregion

}

#endregion Designer generated code
