// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: files/unity_output.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UPC.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from files/unity_output.proto</summary>
  public static partial class UnityOutputReflection {

    #region Descriptor
    /// <summary>File descriptor for files/unity_output.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityOutputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhmaWxlcy91bml0eV9vdXRwdXQucHJvdG8SFGNvbW11bmljYXRvcl9vYmpl",
            "Y3RzGidmaWxlcy91bml0eV9pbml0aWFsaXphdGlvbl9vdXRwdXQucHJvdG8a",
            "E2ZpbGVzL2NvbW1hbmQucHJvdG8inAEKEFVuaXR5T3V0cHV0UHJvdG8SUwoV",
            "aW5pdGlhbGl6YXRpb25fb3V0cHV0GAEgASgLMjQuY29tbXVuaWNhdG9yX29i",
            "amVjdHMuVW5pdHlJbml0aWFsaXphdGlvbk91dHB1dFByb3RvEjMKB2NvbW1h",
            "bmQYAiABKA4yIi5jb21tdW5pY2F0b3Jfb2JqZWN0cy5Db21tYW5kUHJvdG9C",
            "GqoCF1VQQy5Db21tdW5pY2F0b3JPYmplY3RzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::UPC.CommunicatorObjects.UnityInitializationOutputReflection.Descriptor, global::UPC.CommunicatorObjects.CommandReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UPC.CommunicatorObjects.UnityOutputProto), global::UPC.CommunicatorObjects.UnityOutputProto.Parser, new[]{ "InitializationOutput", "Command" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityOutputProto : pb::IMessage<UnityOutputProto> {
    private static readonly pb::MessageParser<UnityOutputProto> _parser = new pb::MessageParser<UnityOutputProto>(() => new UnityOutputProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityOutputProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UPC.CommunicatorObjects.UnityOutputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityOutputProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityOutputProto(UnityOutputProto other) : this() {
      initializationOutput_ = other.initializationOutput_ != null ? other.initializationOutput_.Clone() : null;
      command_ = other.command_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityOutputProto Clone() {
      return new UnityOutputProto(this);
    }

    /// <summary>Field number for the "initialization_output" field.</summary>
    public const int InitializationOutputFieldNumber = 1;
    private global::UPC.CommunicatorObjects.UnityInitializationOutputProto initializationOutput_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::UPC.CommunicatorObjects.UnityInitializationOutputProto InitializationOutput {
      get { return initializationOutput_; }
      set {
        initializationOutput_ = value;
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 2;
    private global::UPC.CommunicatorObjects.CommandProto command_ = global::UPC.CommunicatorObjects.CommandProto.Step;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::UPC.CommunicatorObjects.CommandProto Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityOutputProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityOutputProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(InitializationOutput, other.InitializationOutput)) return false;
      if (Command != other.Command) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (initializationOutput_ != null) hash ^= InitializationOutput.GetHashCode();
      if (Command != global::UPC.CommunicatorObjects.CommandProto.Step) hash ^= Command.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (initializationOutput_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(InitializationOutput);
      }
      if (Command != global::UPC.CommunicatorObjects.CommandProto.Step) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (initializationOutput_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitializationOutput);
      }
      if (Command != global::UPC.CommunicatorObjects.CommandProto.Step) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityOutputProto other) {
      if (other == null) {
        return;
      }
      if (other.initializationOutput_ != null) {
        if (initializationOutput_ == null) {
          InitializationOutput = new global::UPC.CommunicatorObjects.UnityInitializationOutputProto();
        }
        InitializationOutput.MergeFrom(other.InitializationOutput);
      }
      if (other.Command != global::UPC.CommunicatorObjects.CommandProto.Step) {
        Command = other.Command;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (initializationOutput_ == null) {
              InitializationOutput = new global::UPC.CommunicatorObjects.UnityInitializationOutputProto();
            }
            input.ReadMessage(InitializationOutput);
            break;
          }
          case 16: {
            Command = (global::UPC.CommunicatorObjects.CommandProto) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
