// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mlagents/envs/communicator_objects/unity_rl_input.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from mlagents/envs/communicator_objects/unity_rl_input.proto</summary>
  public static partial class UnityRlInputReflection {

    #region Descriptor
    /// <summary>File descriptor for mlagents/envs/communicator_objects/unity_rl_input.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityRlInputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjdtbGFnZW50cy9lbnZzL2NvbW11bmljYXRvcl9vYmplY3RzL3VuaXR5X3Js",
            "X2lucHV0LnByb3RvEhRjb21tdW5pY2F0b3Jfb2JqZWN0cxo2bWxhZ2VudHMv",
            "ZW52cy9jb21tdW5pY2F0b3Jfb2JqZWN0cy9icmFpbl9hY3Rpb25zLnByb3Rv",
            "Gj9tbGFnZW50cy9lbnZzL2NvbW11bmljYXRvcl9vYmplY3RzL2Vudmlyb25t",
            "ZW50X3BhcmFtZXRlcnMucHJvdG8aMG1sYWdlbnRzL2VudnMvY29tbXVuaWNh",
            "dG9yX29iamVjdHMvY29tbWFuZC5wcm90byLaAgoRVW5pdHlSTElucHV0UHJv",
            "dG8SUAoNYnJhaW5fYWN0aW9ucxgBIAMoCzI5LmNvbW11bmljYXRvcl9vYmpl",
            "Y3RzLlVuaXR5UkxJbnB1dFByb3RvLkJyYWluQWN0aW9uc0VudHJ5ElAKFmVu",
            "dmlyb25tZW50X3BhcmFtZXRlcnMYAiABKAsyMC5jb21tdW5pY2F0b3Jfb2Jq",
            "ZWN0cy5FbnZpcm9ubWVudFBhcmFtZXRlcnNQcm90bxITCgtpc190cmFpbmlu",
            "ZxgDIAEoCBIzCgdjb21tYW5kGAQgASgOMiIuY29tbXVuaWNhdG9yX29iamVj",
            "dHMuQ29tbWFuZFByb3RvGlcKEUJyYWluQWN0aW9uc0VudHJ5EgsKA2tleRgB",
            "IAEoCRIxCgV2YWx1ZRgCIAEoCzIiLmNvbW11bmljYXRvcl9vYmplY3RzLkJy",
            "YWluQWN0aW9uczoCOAFCH6oCHE1MQWdlbnRzLkNvbW11bmljYXRvck9iamVj",
            "dHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.CommunicatorObjects.BrainActionsReflection.Descriptor, global::MLAgents.CommunicatorObjects.EnvironmentParametersReflection.Descriptor, global::MLAgents.CommunicatorObjects.CommandReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.UnityRLInputProto), global::MLAgents.CommunicatorObjects.UnityRLInputProto.Parser, new[]{ "BrainActions", "EnvironmentParameters", "IsTraining", "Command" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityRLInputProto : pb::IMessage<UnityRLInputProto> {
    private static readonly pb::MessageParser<UnityRLInputProto> _parser = new pb::MessageParser<UnityRLInputProto>(() => new UnityRLInputProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityRLInputProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.CommunicatorObjects.UnityRlInputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLInputProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLInputProto(UnityRLInputProto other) : this() {
      brainActions_ = other.brainActions_.Clone();
      environmentParameters_ = other.environmentParameters_ != null ? other.environmentParameters_.Clone() : null;
      isTraining_ = other.isTraining_;
      command_ = other.command_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLInputProto Clone() {
      return new UnityRLInputProto(this);
    }

    /// <summary>Field number for the "brain_actions" field.</summary>
    public const int BrainActionsFieldNumber = 1;
    private static readonly pbc::MapField<string, global::MLAgents.CommunicatorObjects.BrainActions>.Codec _map_brainActions_codec
        = new pbc::MapField<string, global::MLAgents.CommunicatorObjects.BrainActions>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::MLAgents.CommunicatorObjects.BrainActions.Parser), 10);
    private readonly pbc::MapField<string, global::MLAgents.CommunicatorObjects.BrainActions> brainActions_ = new pbc::MapField<string, global::MLAgents.CommunicatorObjects.BrainActions>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::MLAgents.CommunicatorObjects.BrainActions> BrainActions {
      get { return brainActions_; }
    }

    /// <summary>Field number for the "environment_parameters" field.</summary>
    public const int EnvironmentParametersFieldNumber = 2;
    private global::MLAgents.CommunicatorObjects.EnvironmentParametersProto environmentParameters_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.EnvironmentParametersProto EnvironmentParameters {
      get { return environmentParameters_; }
      set {
        environmentParameters_ = value;
      }
    }

    /// <summary>Field number for the "is_training" field.</summary>
    public const int IsTrainingFieldNumber = 3;
    private bool isTraining_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsTraining {
      get { return isTraining_; }
      set {
        isTraining_ = value;
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 4;
    private global::MLAgents.CommunicatorObjects.CommandProto command_ = global::MLAgents.CommunicatorObjects.CommandProto.Step;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.CommandProto Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityRLInputProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityRLInputProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!BrainActions.Equals(other.BrainActions)) return false;
      if (!object.Equals(EnvironmentParameters, other.EnvironmentParameters)) return false;
      if (IsTraining != other.IsTraining) return false;
      if (Command != other.Command) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= BrainActions.GetHashCode();
      if (environmentParameters_ != null) hash ^= EnvironmentParameters.GetHashCode();
      if (IsTraining != false) hash ^= IsTraining.GetHashCode();
      if (Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) hash ^= Command.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      brainActions_.WriteTo(output, _map_brainActions_codec);
      if (environmentParameters_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EnvironmentParameters);
      }
      if (IsTraining != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsTraining);
      }
      if (Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += brainActions_.CalculateSize(_map_brainActions_codec);
      if (environmentParameters_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EnvironmentParameters);
      }
      if (IsTraining != false) {
        size += 1 + 1;
      }
      if (Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityRLInputProto other) {
      if (other == null) {
        return;
      }
      brainActions_.Add(other.brainActions_);
      if (other.environmentParameters_ != null) {
        if (environmentParameters_ == null) {
          EnvironmentParameters = new global::MLAgents.CommunicatorObjects.EnvironmentParametersProto();
        }
        EnvironmentParameters.MergeFrom(other.EnvironmentParameters);
      }
      if (other.IsTraining != false) {
        IsTraining = other.IsTraining;
      }
      if (other.Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) {
        Command = other.Command;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            brainActions_.AddEntriesFrom(input, _map_brainActions_codec);
            break;
          }
          case 18: {
            if (environmentParameters_ == null) {
              EnvironmentParameters = new global::MLAgents.CommunicatorObjects.EnvironmentParametersProto();
            }
            input.ReadMessage(EnvironmentParameters);
            break;
          }
          case 24: {
            IsTraining = input.ReadBool();
            break;
          }
          case 32: {
            Command = (global::MLAgents.CommunicatorObjects.CommandProto) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
