// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mlagents/envs/communicator_objects/unity_initialization_input.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from mlagents/envs/communicator_objects/unity_initialization_input.proto</summary>
  public static partial class UnityInitializationInputReflection {

    #region Descriptor
    /// <summary>File descriptor for mlagents/envs/communicator_objects/unity_initialization_input.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityInitializationInputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkNtbGFnZW50cy9lbnZzL2NvbW11bmljYXRvcl9vYmplY3RzL3VuaXR5X2lu",
            "aXRpYWxpemF0aW9uX2lucHV0LnByb3RvEhRjb21tdW5pY2F0b3Jfb2JqZWN0",
            "cxo9bWxhZ2VudHMvZW52cy9jb21tdW5pY2F0b3Jfb2JqZWN0cy9lbmdpbmVf",
            "Y29uZmlndXJhdGlvbi5wcm90byJ7Ch1Vbml0eUluaXRpYWxpemF0aW9uSW5w",
            "dXRQcm90bxJMChRlbmdpbmVfY29uZmlndXJhdGlvbhgBIAEoCzIuLmNvbW11",
            "bmljYXRvcl9vYmplY3RzLkVuZ2luZUNvbmZpZ3VyYXRpb25Qcm90bxIMCgRz",
            "ZWVkGAIgASgFQh+qAhxNTEFnZW50cy5Db21tdW5pY2F0b3JPYmplY3RzYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.CommunicatorObjects.EngineConfigurationReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.UnityInitializationInputProto), global::MLAgents.CommunicatorObjects.UnityInitializationInputProto.Parser, new[]{ "EngineConfiguration", "Seed" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityInitializationInputProto : pb::IMessage<UnityInitializationInputProto> {
    private static readonly pb::MessageParser<UnityInitializationInputProto> _parser = new pb::MessageParser<UnityInitializationInputProto>(() => new UnityInitializationInputProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityInitializationInputProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.CommunicatorObjects.UnityInitializationInputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationInputProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationInputProto(UnityInitializationInputProto other) : this() {
      engineConfiguration_ = other.engineConfiguration_ != null ? other.engineConfiguration_.Clone() : null;
      seed_ = other.seed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationInputProto Clone() {
      return new UnityInitializationInputProto(this);
    }

    /// <summary>Field number for the "engine_configuration" field.</summary>
    public const int EngineConfigurationFieldNumber = 1;
    private global::MLAgents.CommunicatorObjects.EngineConfigurationProto engineConfiguration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.EngineConfigurationProto EngineConfiguration {
      get { return engineConfiguration_; }
      set {
        engineConfiguration_ = value;
      }
    }

    /// <summary>Field number for the "seed" field.</summary>
    public const int SeedFieldNumber = 2;
    private int seed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Seed {
      get { return seed_; }
      set {
        seed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityInitializationInputProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityInitializationInputProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(EngineConfiguration, other.EngineConfiguration)) return false;
      if (Seed != other.Seed) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (engineConfiguration_ != null) hash ^= EngineConfiguration.GetHashCode();
      if (Seed != 0) hash ^= Seed.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (engineConfiguration_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(EngineConfiguration);
      }
      if (Seed != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Seed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (engineConfiguration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EngineConfiguration);
      }
      if (Seed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seed);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityInitializationInputProto other) {
      if (other == null) {
        return;
      }
      if (other.engineConfiguration_ != null) {
        if (engineConfiguration_ == null) {
          EngineConfiguration = new global::MLAgents.CommunicatorObjects.EngineConfigurationProto();
        }
        EngineConfiguration.MergeFrom(other.EngineConfiguration);
      }
      if (other.Seed != 0) {
        Seed = other.Seed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (engineConfiguration_ == null) {
              EngineConfiguration = new global::MLAgents.CommunicatorObjects.EngineConfigurationProto();
            }
            input.ReadMessage(EngineConfiguration);
            break;
          }
          case 16: {
            Seed = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
