// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mlagents/envs/communicator_objects/unity_initialization_output.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UPC.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from mlagents/envs/communicator_objects/unity_initialization_output.proto</summary>
  public static partial class UnityInitializationOutputReflection {

    #region Descriptor
    /// <summary>File descriptor for mlagents/envs/communicator_objects/unity_initialization_output.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityInitializationOutputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkRtbGFnZW50cy9lbnZzL2NvbW11bmljYXRvcl9vYmplY3RzL3VuaXR5X2lu",
            "aXRpYWxpemF0aW9uX291dHB1dC5wcm90bxIUY29tbXVuaWNhdG9yX29iamVj",
            "dHMaOW1sYWdlbnRzL2VudnMvY29tbXVuaWNhdG9yX29iamVjdHMvYnJhaW5f",
            "cGFyYW1ldGVycy5wcm90byKnAgoeVW5pdHlJbml0aWFsaXphdGlvbk91dHB1",
            "dFByb3RvEgwKBG5hbWUYASABKAkSRAoQYnJhaW5fcGFyYW1ldGVycxgCIAMo",
            "CzIqLmNvbW11bmljYXRvcl9vYmplY3RzLkJyYWluUGFyYW1ldGVyc1Byb3Rv",
            "EnIKGGRlZmF1bHRfcmVzZXRfcGFyYW1ldGVycxgDIAMoCzJQLmNvbW11bmlj",
            "YXRvcl9vYmplY3RzLlVuaXR5SW5pdGlhbGl6YXRpb25PdXRwdXRQcm90by5E",
            "ZWZhdWx0UmVzZXRQYXJhbWV0ZXJzRW50cnkaPQobRGVmYXVsdFJlc2V0UGFy",
            "YW1ldGVyc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoAjoCOAFC",
            "H6oCHE1MQWdlbnRzLkNvbW11bmljYXRvck9iamVjdHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::UPC.CommunicatorObjects.BrainParametersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UPC.CommunicatorObjects.UnityInitializationOutputProto), global::UPC.CommunicatorObjects.UnityInitializationOutputProto.Parser, new[]{ "Name", "BrainParameters", "DefaultResetParameters" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityInitializationOutputProto : pb::IMessage<UnityInitializationOutputProto> {
    private static readonly pb::MessageParser<UnityInitializationOutputProto> _parser = new pb::MessageParser<UnityInitializationOutputProto>(() => new UnityInitializationOutputProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityInitializationOutputProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UPC.CommunicatorObjects.UnityInitializationOutputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationOutputProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationOutputProto(UnityInitializationOutputProto other) : this() {
      name_ = other.name_;
      brainParameters_ = other.brainParameters_.Clone();
      defaultResetParameters_ = other.defaultResetParameters_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInitializationOutputProto Clone() {
      return new UnityInitializationOutputProto(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "brain_parameters" field.</summary>
    public const int BrainParametersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::UPC.CommunicatorObjects.BrainParametersProto> _repeated_brainParameters_codec
        = pb::FieldCodec.ForMessage(18, global::UPC.CommunicatorObjects.BrainParametersProto.Parser);
    private readonly pbc::RepeatedField<global::UPC.CommunicatorObjects.BrainParametersProto> brainParameters_ = new pbc::RepeatedField<global::UPC.CommunicatorObjects.BrainParametersProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::UPC.CommunicatorObjects.BrainParametersProto> BrainParameters {
      get { return brainParameters_; }
    }

    /// <summary>Field number for the "default_reset_parameters" field.</summary>
    public const int DefaultResetParametersFieldNumber = 3;
    private static readonly pbc::MapField<string, float>.Codec _map_defaultResetParameters_codec
        = new pbc::MapField<string, float>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForFloat(21, 0F), 26);
    private readonly pbc::MapField<string, float> defaultResetParameters_ = new pbc::MapField<string, float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, float> DefaultResetParameters {
      get { return defaultResetParameters_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityInitializationOutputProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityInitializationOutputProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!brainParameters_.Equals(other.brainParameters_)) return false;
      if (!DefaultResetParameters.Equals(other.DefaultResetParameters)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= brainParameters_.GetHashCode();
      hash ^= DefaultResetParameters.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      brainParameters_.WriteTo(output, _repeated_brainParameters_codec);
      defaultResetParameters_.WriteTo(output, _map_defaultResetParameters_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += brainParameters_.CalculateSize(_repeated_brainParameters_codec);
      size += defaultResetParameters_.CalculateSize(_map_defaultResetParameters_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityInitializationOutputProto other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      brainParameters_.Add(other.brainParameters_);
      defaultResetParameters_.Add(other.defaultResetParameters_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            brainParameters_.AddEntriesFrom(input, _repeated_brainParameters_codec);
            break;
          }
          case 26: {
            defaultResetParameters_.AddEntriesFrom(input, _map_defaultResetParameters_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
