// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mlagents/envs/communicator_objects/unity_input.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from mlagents/envs/communicator_objects/unity_input.proto</summary>
  public static partial class UnityInputReflection {

    #region Descriptor
    /// <summary>File descriptor for mlagents/envs/communicator_objects/unity_input.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityInputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRtbGFnZW50cy9lbnZzL2NvbW11bmljYXRvcl9vYmplY3RzL3VuaXR5X2lu",
            "cHV0LnByb3RvEhRjb21tdW5pY2F0b3Jfb2JqZWN0cxpDbWxhZ2VudHMvZW52",
            "cy9jb21tdW5pY2F0b3Jfb2JqZWN0cy91bml0eV9pbml0aWFsaXphdGlvbl9p",
            "bnB1dC5wcm90bxowbWxhZ2VudHMvZW52cy9jb21tdW5pY2F0b3Jfb2JqZWN0",
            "cy9jb21tYW5kLnByb3RvIpkBCg9Vbml0eUlucHV0UHJvdG8SUQoUaW5pdGlh",
            "bGl6YXRpb25faW5wdXQYASABKAsyMy5jb21tdW5pY2F0b3Jfb2JqZWN0cy5V",
            "bml0eUluaXRpYWxpemF0aW9uSW5wdXRQcm90bxIzCgdjb21tYW5kGAIgASgO",
            "MiIuY29tbXVuaWNhdG9yX29iamVjdHMuQ29tbWFuZFByb3RvQh+qAhxNTEFn",
            "ZW50cy5Db21tdW5pY2F0b3JPYmplY3RzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.CommunicatorObjects.UnityInitializationInputReflection.Descriptor, global::MLAgents.CommunicatorObjects.CommandReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.UnityInputProto), global::MLAgents.CommunicatorObjects.UnityInputProto.Parser, new[]{ "InitializationInput", "Command" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityInputProto : pb::IMessage<UnityInputProto> {
    private static readonly pb::MessageParser<UnityInputProto> _parser = new pb::MessageParser<UnityInputProto>(() => new UnityInputProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityInputProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.CommunicatorObjects.UnityInputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInputProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInputProto(UnityInputProto other) : this() {
      initializationInput_ = other.initializationInput_ != null ? other.initializationInput_.Clone() : null;
      command_ = other.command_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInputProto Clone() {
      return new UnityInputProto(this);
    }

    /// <summary>Field number for the "initialization_input" field.</summary>
    public const int InitializationInputFieldNumber = 1;
    private global::MLAgents.CommunicatorObjects.UnityInitializationInputProto initializationInput_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.UnityInitializationInputProto InitializationInput {
      get { return initializationInput_; }
      set {
        initializationInput_ = value;
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 2;
    private global::MLAgents.CommunicatorObjects.CommandProto command_ = global::MLAgents.CommunicatorObjects.CommandProto.Step;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.CommandProto Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityInputProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityInputProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(InitializationInput, other.InitializationInput)) return false;
      if (Command != other.Command) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (initializationInput_ != null) hash ^= InitializationInput.GetHashCode();
      if (Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) hash ^= Command.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (initializationInput_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(InitializationInput);
      }
      if (Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (initializationInput_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InitializationInput);
      }
      if (Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityInputProto other) {
      if (other == null) {
        return;
      }
      if (other.initializationInput_ != null) {
        if (initializationInput_ == null) {
          InitializationInput = new global::MLAgents.CommunicatorObjects.UnityInitializationInputProto();
        }
        InitializationInput.MergeFrom(other.InitializationInput);
      }
      if (other.Command != global::MLAgents.CommunicatorObjects.CommandProto.Step) {
        Command = other.Command;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (initializationInput_ == null) {
              InitializationInput = new global::MLAgents.CommunicatorObjects.UnityInitializationInputProto();
            }
            input.ReadMessage(InitializationInput);
            break;
          }
          case 16: {
            Command = (global::MLAgents.CommunicatorObjects.CommandProto) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
