# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlagents/envs/communicator_objects/brain_actions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlagents/envs/communicator_objects/brain_actions.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=b'\252\002\034MLAgents.CommunicatorObjects',
  serialized_pb=b'\n6mlagents/envs/communicator_objects/brain_actions.proto\x12\x14\x63ommunicator_objects\"*\n\x0c\x42rainActions\x12\x1a\n\x0estackedActions\x18\x01 \x03(\x02\x42\x02\x10\x01\x42\x1f\xaa\x02\x1cMLAgents.CommunicatorObjectsb\x06proto3'
)

_BRAINACTIONS = _descriptor.Descriptor(
  name='BrainActions',
  full_name='communicator_objects.BrainActions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stackedActions', full_name='communicator_objects.BrainActions.stackedActions', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['BrainActions'] = _BRAINACTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BrainActions = _reflection.GeneratedProtocolMessageType('BrainActions', (_message.Message,), {
  'DESCRIPTOR' : _BRAINACTIONS,
  '__module__' : 'mlagents.envs.communicator_objects.brain_actions_pb2'
  # @@protoc_insertion_point(class_scope:communicator_objects.BrainActions)
  })
_sym_db.RegisterMessage(BrainActions)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\034MLAgents.CommunicatorObjects'))
_BRAINACTIONS.fields_by_name['stackedActions']._options = None
# @@protoc_insertion_point(module_scope)
