# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlagents/envs/communicator_objects/unity_output.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlagents.envs.communicator_objects import unity_initialization_output_pb2 as mlagents_dot_envs_dot_communicator__objects_dot_unity__initialization__output__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlagents/envs/communicator_objects/unity_output.proto',
  package='communicator_objects',
  syntax='proto3',
  serialized_options=b'\252\002\034MLAgents.CommunicatorObjects',
  serialized_pb=b'\n5mlagents/envs/communicator_objects/unity_output.proto\x12\x14\x63ommunicator_objects\x1a\x44mlagents/envs/communicator_objects/unity_initialization_output.proto\"g\n\x10UnityOutputProto\x12S\n\x15initialization_output\x18\x02 \x01(\x0b\x32\x34.communicator_objects.UnityInitializationOutputProtoB\x1f\xaa\x02\x1cMLAgents.CommunicatorObjectsb\x06proto3'
  ,
  dependencies=[mlagents_dot_envs_dot_communicator__objects_dot_unity__initialization__output__pb2.DESCRIPTOR,])




_UNITYOUTPUTPROTO = _descriptor.Descriptor(
  name='UnityOutputProto',
  full_name='communicator_objects.UnityOutputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initialization_output', full_name='communicator_objects.UnityOutputProto.initialization_output', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=252,
)

_UNITYOUTPUTPROTO.fields_by_name['initialization_output'].message_type = mlagents_dot_envs_dot_communicator__objects_dot_unity__initialization__output__pb2._UNITYINITIALIZATIONOUTPUTPROTO
DESCRIPTOR.message_types_by_name['UnityOutputProto'] = _UNITYOUTPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnityOutputProto = _reflection.GeneratedProtocolMessageType('UnityOutputProto', (_message.Message,), {
  'DESCRIPTOR' : _UNITYOUTPUTPROTO,
  '__module__' : 'mlagents.envs.communicator_objects.unity_output_pb2'
  # @@protoc_insertion_point(class_scope:communicator_objects.UnityOutputProto)
  })
_sym_db.RegisterMessage(UnityOutputProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\034MLAgents.CommunicatorObjects'))
# @@protoc_insertion_point(module_scope)
